version: 1
labels:
  - label: "docs"
    files:
      - "docs/*"
  - label: "flutter"
    files:
      - "flutter_project/*"
  - label: "HTML-CSS-JS"
    files:
      - "HTML-CSS-JAVASCRIPT Projects/.*"
  - label: "Python"
    files:
      - "Python Projects/*"
  - label: "xsmall-diff"
    size-below: 10
  - label: "small-diff"
    size-above: 9
    size-below: 100
  - label: "medium-diff"
    size-above: 99
    size-below: 500
  - label: "large-diff"
    size-above: 499
    size-below: 1000
  - label: "xlarge-diff"
    size-above: 999
